# Generated by Django 3.2.8 on 2021-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_auto_20211103_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/pfp_default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
