# Generated by Django 3.2.8 on 2021-11-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_auto_20211112_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
